http://localhost:8080/employee
###
http://localhost:8080/employee/add?firstName=Ivan
###
http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov2
###
http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov3
###
http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov4
###
http://localhost:8080/employee/remove?firstName=Ivan&lastName=Ivanov2
###
http://localhost:8080/employee/find?firstName=Ivan
###
http://localhost:8080/employee/find?firstName=Ivan&lastName=Ivanov3