http://localhost:8080/employee
###
http://localhost:8080/employee/add?firstName=Ivan
###
http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov&department=2&salary=1000
###
http://localhost:8080/employee/add?firstName=iVan&lastName=иВАНОВ&department=2&salary=2000
###
http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov4&department=3&salary=1500
###
http://localhost:8080/employee/remove?firstName=Ivan&lastName=Ivanov3&department=2&salary=2000
###
http://localhost:8080/employee/find?firstName=Ivan
###
http://localhost:8080/department/all
###
http://localhost:8080/department/min-salary?department=2
###
http://localhost:8080/department/max-salary?department=2
###
http://localhost:8080/department/all?department=2
###


